package pack;
// Generated Feb 4, 2017 10:14:58 AM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String rollno;
     private String address;
     private String phno;
     private String email;

    public Student() {
    }

    public Student(String name, String rollno, String address, String phno, String email) {
       this.name = name;
       this.rollno = rollno;
       this.address = address;
       this.phno = phno;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRollno() {
        return this.rollno;
    }
    
    public void setRollno(String rollno) {
        this.rollno = rollno;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhno() {
        return this.phno;
    }
    
    public void setPhno(String phno) {
        this.phno = phno;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


